### ISSUE TITLE
Differentiate between no expiration, expiration and unknown

### ISSUE THREAD

**Issue by tbm** [redstreet/fava_miler#2]
If `expiry-months` is not define, the date of the last transaction is used.  I don't think that's ideal since:

* Some miles have no expiration. I think in that case the field should be blank
* It might not be defined, i.e. unknown, in which case it should say "unknown" or something? (or be blank, but then no expiration should say "none")

I tried something like this but then the sorting broke:

```
        if 'expiry-months' in meta:
            expiry_months = meta['expiry-months']
            if expiry_months:
                expiry = row.latest_transaction + datetime.timedelta(int(expiry_months)*365/12)
            else:
                expiry = ''
        else:
            expiry = 'unknown'
```

What's the best way to handle this in your view?

**Comment by redstreet** [comment]
Good point, thanks, check out the update.

**Comment by tbm** [comment]
You addressed the "no expiration" point, but not the "unknown".

If no `expiry-months` is set, you show the last transaction, but wouldn't it be better to show an empty field?

**Comment by redstreet** [comment]
The way I think about it is, "unknown" is just a TODO item where I need to look up the policy on a website or some such and add `expiry-months`. Until then, I choose the most conservative date possible for expiry, which is the date of latest transaction. This makes it go to the top of the table when sorted by date, which grabs my attention, and lets me get to the TODO.

This may not fit everyone's exact preferences, but it works, and keeps the clutter low IMHO.
