### ISSUE TITLE
module 'beancount.core.getters' has no attribute 'get_commodity_directives' with beancount <2.3.1

### ISSUE THREAD

**Issue by tbm** [redstreet/fava_miler#6]
```
  File "/home/tbm/.local/lib/python3.7/site-packages/fava_miler/common/favainvestorapi.py", line 16, in get_commodity_map
    return getters.get_commodity_map(self.ledger.entries)
AttributeError: module 'beancount.core.getters' has no attribute 'get_commodity_map'
```

You  need a dependency on beancount 2.3.3.

**Comment by tbm** [comment]
Uhm, sorry, what I said doesn't make sense.  Let me check what's really going on.

**Comment by tbm** [comment]
Right, with fava_miler 0.2.2 and beancount 2.3.0 you get:

```
  File "/home/tbm/.local/lib/python3.7/site-packages/fava_miler/common/favainvestorapi.py", line 16, in get_commodity_directives
    return getters.get_commodity_directives(self.ledger.entries)
AttributeError: module 'beancount.core.getters' has no attribute 'get_commodity_directives'
```

You need a dependency on 2.3.1.

**Comment by redstreet** [comment]
`get_commodity_directives` newly replaced `get_commodity_map` in beancount.
`get_commodity_map` works fine with older versions of beancount.

Two changes are needed: dependency and using `get_commodity_directives` instead of the older `get_commodity_map`.

Thanks for filing this, @tbm !

**Comment by redstreet** [comment]
Bumped in 35670aa.
